language: php
php:
- '5.6'

script: echo "We don't have tests yet :("

before_deploy:
- sh package.sh

deploy:
  provider: releases
  name: "$TRAVIS_TAG"
  api_key:
    secure: cuxCq7BuyO8mGuIxaKpbZNDhEqC3GTAE9Pc9juTdzAPdxQ1q31bBg7EyLXbh9JoEW6ZNNfBASjYBoArvMnpD/RVkxS4zCC0l5ncAJZa8ArhTD0e1nxegAC/4/LlsgoRREtb/EoPOE9thzd+31gZq/YDBjbeBsS0Sj+D/YRlsZm+1Czea1WbXm81lCgVefemAeq77zRXfqoiSC74xkVcKZPONMJe57s4O2YLooqRo5xcEz6nqU9xVSfDfPVu0EchaEUO1JBMNXgwG+6HmsCYCtcCUPp6uqA8LHff0sOjAQnYfFNw/ge2ihnpyXWrCrTvS5pz4je8eIeR03usyN627yOdG6x9xTgDVnPaqGmzqlYJHMbBcgkuxvWVCO2sasWQkqo8KKA1uGmv64Y7Y6x68sixu6JOD0zFRpz5WLXZp7Kguz9P0rkIkOmFGGlzu+wKA+JLft4nHXDEaInna88GobUeBh/Z66643KIXOZl3MUc4Z+N2rLH4twuRKn7Fs8BqG34iEF5xqBlhQjhvsE2q2W09sxO8jq4VHRFTpQ4UMVUZzJs2+ZEbF8N4rDoCT9u5Up+rJsKWH16saO3iuiuugYNFswh8LA+hfsTC5Yu8u0TsSUqH0c+wvVsL2aJV/1KYriOhtW2TqndlpSwfpMCskxZDTECZLvcPxiBsT43bb/zU=
  file: "woocommerce-transbank.zip"
  skip_cleanup: true
  on:
    repo: TransbankDevelopers/transbank-plugin-woocommerce-webpay
    tags: true
